spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/frg
    username: postgres
    password: Tokym123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    root: INFO
    com.myapp: DEBUG
